/*
 * Сервис проверки статуса банкоматов
 * Сервис, возвращающий информацию о банкоматах Альфа-Банка
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@alfabank.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.alfabattle.borisov.atms.model.alfabank;

import lombok.Data;

@Data
public class JSONResponseBankATMDetails {

  private BankATMDetails data;
  private Error error;
  private Boolean success;
  private Integer total;

}

